---
splunk:
  app_paths:
    default: /opt/splunk/etc/apps
  conf:
    - key: user-prefs
      value:
        directory: /opt/splunk/etc/users/admin/user-prefs/local
        content:
          general:
            default_namespace: splunk_typegen
            search_syntax_highlighting: dark
    - key: indexes
          value:
            directory: /opt/splunk/etc/system/local
            content:
              test:
                homePath: $SPLUNK_DB/test/db
                coldPath: $SPLUNK_DB/test/colddb
                thawedPath: $SPLUNK_DB/test/thaweddb            