version: "3.6"

services:
  so1:
    image: ${SPLUNK_IMAGE:-splunk/splunk:7.3.0}
    container_name: so1
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=1234Abc@
      - SPLUNK_ROLE=splunk_standalone
      - SPLUNK_HOME=/opt/splunk
      - SPLUNK_APPS_URL=https://github.com/marceloapps/splunk_typegen_docker/raw/master/splunk_typegen.spl
    ports:
      - 8000:8000