version: "3.6"

services:
  so1:
    image: marceloarakaki/splunk:latest
    container_name: so1
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_LICENSE_URI=Free
      - SPLUNK_PASSWORD=1234Abc@
      - SPLUNK_ROLE=splunk_standalone
      - SPLUNK_HOME=/opt/splunk
      - SPLUNK_IGNORE_LICENSE=true
      - SPLUNK_DEFAULTS_HTTP_MAX_TIMEOUT=50
      - SPLUNK_DEFAULTS_HTTP_MAX_RETRIES=3
      - SPLUNK_DEFAULTS_HTTP_MAX_DELAY=10
    ports:
      - 8000:8000