version: '3'

services:
  typegen_nginx:
    build:
      dockerfile: nginx.dockerfile
      context: .
    image: typegen_nginx
    container_name: typegen_nginx
    ports:
      - 80:80
    depends_on: 
      - "typegen_splunk1"
      - "typegen_splunk2"
      - "typegen_splunk3"
    networks: 
      - techstack_nets      

  typegen_splunk1:
    build:
      dockerfile: splunk_typegen.dockerfile
      context: .
    image: splunk_typegen #marceloarakaki/splunk:latest
    container_name: typegen1
    ports:
      - "8000"
    networks: 
      - techstack_nets

  typegen_splunk2:
    build:
      dockerfile: splunk_typegen.dockerfile
      context: .
    image: splunk_typegen #marceloarakaki/splunk:latest
    container_name: typegen2
    ports:
      - "8000"
    networks: 
      - techstack_nets      

  typegen_splunk3:
    build:
      dockerfile: splunk_typegen.dockerfile
      context: .
    image: splunk_typegen #marceloarakaki/splunk:latest
    container_name: typegen3
    ports:
      - "8000"
    networks: 
      - techstack_nets      

networks:
  techstack_nets:
    driver: bridge